name: Update Agent List

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies clean
        run: |
          rm -rf node_modules
          npm ci

      - name: Run scraper
        run: node scraper/scrape-agents.mjs

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add agents.json
          git commit -m "Update agent list [auto]" || echo "No changes"
          git push
